###############################################################
#  Generated by:      Cadence Innovus 19.10-p002_1
#  OS:                Linux x86_64(Host ID srv-eda-04)
#  Generated on:      Wed May 25 01:22:15 2022
#  Design:            top
#  Command:           saveTestcase
###############################################################
current_design top
set_clock_gating_check -rise -setup 0 
set_clock_gating_check -fall -setup 0 
