
// Generated by Cadence Genus(TM) Synthesis Solution 19.10-p002_1
// Generated on: May 25 2022 20:10:20 MSK (May 25 2022 17:10:20 UTC)

// Verification Directory fv/commutator 

module commutator(inputs, control, clk, outputs);
  input [7:0] inputs;
  input [2:0] control, clk;
  output [2:0] outputs;
  wire [7:0] inputs;
  wire [2:0] control, clk;
  wire [2:0] outputs;
  wire [8:0] mem_out;
  wire UNCONNECTED, UNCONNECTED0, UNCONNECTED1, UNCONNECTED2,
       UNCONNECTED3, UNCONNECTED4, UNCONNECTED5, UNCONNECTED6;
  wire UNCONNECTED7, n_0, n_1, n_2, n_3, n_4, n_5, n_6;
  wire n_7, n_8;
  MXI4XL g754(.A (n_0), .B (n_1), .C (n_3), .D (n_4), .S0 (mem_out[4]),
       .S1 (mem_out[5]), .Y (outputs[1]));
  MX2XL g752(.A (n_7), .B (n_6), .S0 (mem_out[8]), .Y (outputs[2]));
  MX2XL g753(.A (n_8), .B (n_5), .S0 (mem_out[1]), .Y (outputs[0]));
  MX4XL g756(.A (inputs[0]), .B (inputs[1]), .C (inputs[4]), .D
       (inputs[5]), .S0 (mem_out[2]), .S1 (mem_out[0]), .Y (n_8));
  MX4XL g757(.A (inputs[0]), .B (inputs[2]), .C (inputs[4]), .D
       (inputs[6]), .S0 (mem_out[7]), .S1 (mem_out[6]), .Y (n_7));
  MX4XL g755(.A (inputs[1]), .B (inputs[5]), .C (inputs[3]), .D
       (inputs[7]), .S0 (mem_out[6]), .S1 (mem_out[7]), .Y (n_6));
  MX4XL g758(.A (inputs[2]), .B (inputs[6]), .C (inputs[3]), .D
       (inputs[7]), .S0 (mem_out[0]), .S1 (mem_out[2]), .Y (n_5));
  AOI22XL g759(.A0 (inputs[3]), .A1 (mem_out[3]), .B0 (inputs[7]), .B1
       (n_2), .Y (n_4));
  AOI22XL g760(.A0 (inputs[1]), .A1 (mem_out[3]), .B0 (inputs[5]), .B1
       (n_2), .Y (n_3));
  AOI22XL g761(.A0 (inputs[2]), .A1 (mem_out[3]), .B0 (inputs[6]), .B1
       (n_2), .Y (n_1));
  AOI22XL g762(.A0 (inputs[0]), .A1 (mem_out[3]), .B0 (inputs[4]), .B1
       (n_2), .Y (n_0));
  INVXL g767(.A (mem_out[3]), .Y (n_2));
  TLATX1 dd0_dd0_dd1_q_reg(.G (clk[0]), .D (control[1]), .Q
       (mem_out[1]), .QN (UNCONNECTED));
  TLATX1 dd0_dd2_dd1_q_reg(.G (clk[2]), .D (control[1]), .Q
       (mem_out[7]), .QN (UNCONNECTED0));
  TLATX1 dd0_dd2_dd0_q_reg(.G (clk[2]), .D (control[0]), .Q
       (mem_out[6]), .QN (UNCONNECTED1));
  TLATX1 dd0_dd0_dd0_q_reg(.G (clk[0]), .D (control[0]), .Q
       (mem_out[0]), .QN (UNCONNECTED2));
  TLATX1 dd0_dd1_dd2_q_reg(.G (clk[1]), .D (control[2]), .Q
       (mem_out[5]), .QN (UNCONNECTED3));
  TLATX1 dd0_dd1_dd1_q_reg(.G (clk[1]), .D (control[1]), .Q
       (mem_out[4]), .QN (UNCONNECTED4));
  TLATX1 dd0_dd2_dd2_q_reg(.G (clk[2]), .D (control[2]), .Q
       (mem_out[8]), .QN (UNCONNECTED5));
  TLATX1 dd0_dd0_dd2_q_reg(.G (clk[0]), .D (control[2]), .Q
       (mem_out[2]), .QN (UNCONNECTED6));
  TLATX1 dd0_dd1_dd0_q_reg(.G (clk[1]), .D (control[0]), .Q
       (UNCONNECTED7), .QN (mem_out[3]));
endmodule

